# Generated by Django 4.0.6 on 2022-07-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_male_name_male'),
    ]

    operations = [
        migrations.DeleteModel(
            name='male',
        ),
    ]
